--------------------------------------------------------
--  File created - понедельник-но€бр€-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOREIGN_CURRENCY_MARKET_LIB
--------------------------------------------------------

  CREATE TABLE "USER_MARKELOV"."FOREIGN_CURRENCY_MARKET_LIB" 
   (	"VALUTA_ID" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"ENGNAME" VARCHAR2(100 BYTE), 
	"NOMINAL" NUMBER(10,0), 
	"PARENTCODE" VARCHAR2(10 BYTE), 
	"ISO_NUM_CODE" NUMBER(10,0), 
	"ISO_CHAR_CODE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FOREIGN_CURRENCY_MARKET_LIB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_MARKELOV"."FOREIGN_CURRENCY_MARKET_LIB_PK" ON "USER_MARKELOV"."FOREIGN_CURRENCY_MARKET_LIB" ("VALUTA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FOREIGN_CURRENCY_MARKET_LIB
--------------------------------------------------------

  ALTER TABLE "USER_MARKELOV"."FOREIGN_CURRENCY_MARKET_LIB" MODIFY ("VALUTA_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_MARKELOV"."FOREIGN_CURRENCY_MARKET_LIB" ADD CONSTRAINT "FOREIGN_CURRENCY_MARKET_LIB_PK" PRIMARY KEY ("VALUTA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
